FIX tc deletion inside insertion [MACRO-1723]
coparse-inc/libreofficekit pull request #115
Opened 2024-05-01 22:32 UTC by synoet

# Summary of PR
When you create a deletion redline inside the range of an existing insertion redline, the initial redline gets split up.

"Initial Test Redline"(Insertion)
---- *DELETE* "Test" ----
"Initial"(Insertion), "Test"(Deletion), "Redline"(Insertion) 

The existing code would push the RedlineData from the first "Initial" redline to the split "Test" redline.
But this is incorrect, because the "Test" redline has different author information.

These changes should be isolated exclusively to the case where you make a deletion within an existing insertion.

The inverse of this, making an insertion within an existing deletion currently works correctly, and it does not push the data to the split parts.

```cpp
case RedlineType::Insert:
    switch (pRedl->GetType())
    {
        // ... other cases ...

        case RedlineType::Delete:
            if (SwComparePosition::Inside == eCmpPos)
            {
                // split up
                if (*pEnd != *pREnd)
                {
                    SwRangeRedline* pCpy = new SwRangeRedline(*pRedl);
                    pCpy->SetStart(*pEnd);
                    maRedlineTable.Insert(pCpy);
                }
                pRedl->SetEnd(*pStt, pREnd);
                if ((*pStt == *pRStt) && (pRedl->GetContentIdx() == nullptr))
                {
                    maRedlineTable.DeleteAndDestroy(n);
                    bDec = true;
                }
                else if (!pRedl->HasValidRange())
                {
                    // re-insert
                    maRedlineTable.Remove(n);
                    maRedlineTable.Insert(pRedl);
                }
            }
            break;
    }
    break;

```

## Before you submit this PR
This is a **public, open source project**. Confidential or sensitive information should not be included in this description or any comments, including but not limited to links, files, and documents.

*If you're not certain that information is not confidential or sensitive in nature, do not include it.*

- [ ] I have verified that this PR does not include any confidential information

2024-05-01 23:51 UTC, chase reviewed
This fix seems familiar, and I'm worried it will negatively affect the rest of track changes because the push was added but the corresponding pop aren't removed.

This seems like it might be an issue upstream, can you verify @synoet?

Might be a good idea to consult with Collabora about this fix.

2024-05-02 02:18 UTC, synoet commented
@chase I might be wrong but I think there is no need for a correspond pop since we where calling it with `bOwnAsNext = false`

Which I believe would mean that there isn't actually anything that would need to be popped since we aren't directly changing just appending? 

I did do some general test... Though you are right no harm in consulting collabora.
```cpp
void SwRangeRedline::PushData( const SwRangeRedline& rRedl, bool bOwnAsNext )
{
    SwRedlineData* pNew = new SwRedlineData( *rRedl.m_pRedlineData, false );
    if( bOwnAsNext )
    {
        pNew->m_pNext = m_pRedlineData;
        m_pRedlineData = pNew;
    }
    else
    {
        pNew->m_pNext = m_pRedlineData->m_pNext;
        m_pRedlineData->m_pNext = pNew;
    }
}
```

2024-05-02 02:31 UTC, chase commented
> @chase I might be wrong but I think there is no need for a correspond pop since we where calling it with `bOwnAsNext = false`

You very well could be right, but I think consulting with Collabora on this would be best, don't want to introduce regressions.

2024-05-07 11:56 UTC, chase requested changes
Overall good, just need to add the MACRO comments

2024-05-07 11:56 UTC, chase commented on libreoffice-core/sw/source/core/doc/DocumentRedlineManager.cxx
> +                                    // MACRO : {
```suggestion
                                    // MACRO-1723: Fix author when deleting an existing insertion {
```

Please add/fix the remaining code for the rest of the changes

2024-05-07 12:41 UTC, chase requested changes
All proprietary changes need comments

2024-05-07 12:41 UTC, chase commented on libreoffice-core/sw/inc/redline.hxx
Please add comments here as well

2024-05-07 12:41 UTC, chase commented on libreoffice-core/sw/source/core/doc/docredln.cxx
Please add comments here as well

2024-05-07 12:53 UTC, merged