Add red/blue colorization and comparison list formatting
coparse-inc/libreofficekit pull request #63
Opened 2023-09-18 21:34 UTC by gbirman

2023-09-18 21:46 UTC, whutchinson98 commented
For red and blue colors please use the ones I created in falcon that match Words. The blue and red that lok comes with are a bit funky from what I remember

2023-09-19 13:57 UTC, whutchinson98 requested changes

2023-09-19 13:57 UTC, whutchinson98 commented on libreoffice-core/sw/source/uibase/app/swmodul1.cxx
> -static Color lcl_GetAuthorColor(std::size_t nPos)
I don't think we should remove any unused methods that originate from LOK. This can make future rebasing harder. I think it's best to leave this in

2023-09-19 17:47 UTC, whutchinson98 approved these changes

2023-09-19 19:11 UTC, synoet approved these changes

2023-09-19 19:11 UTC, merged